### ISSUE TITLE
Migrate to Lamba?

### ISSUE THREAD

**Issue by DavidKnight247** [ShivanS93/twitter-optom-bot#3]
Hi, have you thought of migrating your bot to Lambda instead of using an EC2 instance? Lots of benefits!

**Comment by shivan-s** [comment]
No I haven't. I will have a look into it! Thank you .

**Comment by shivan-s** [comment]
@DavidKnight247 in fact, I have a digital ocean droplet that I have several projects on there (very economic haha).  I was thinking of migrating this project onto the their since EC2 is starting to charge me money. But I will have a look at Lambda too. Thanks for the suggestion.

**Comment by shivan-s** [comment]
Moved to digital ocean instead.
